---
# defaults file for apache
domain: default
apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"

# On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
# Set this to `true` to remove that default.
apache_remove_default_vhost: false

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
apache_vhosts:
  # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
  - servername: "{{ domain }}",
    serveralias: "www.{{ domain }}",

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

apache_vhosts_ssl: []
 - servername: "{{ domain }}",
   serveralias: "www.{{ domain }}",
   certificate_file: "/etc/ssl/cert/{{ domain }}.crt",
   certificate_key_file: "/etc/ssl/private/{{ domain }}.crt",
#   certificate_chain_file: "/etc/ssl/cert/ca_{{ domain }}.crt",

apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - proxy.load

apache_mods_disabled: []

apache_state: started
apache_restart_state: restarted

apache_packages_state: present
